version: '2'
services:
  user-app:
    image: user-app
    build: MovieCruiserAuthenticationService/
    restart: always
    network_mode: host
    ports:
    - 8085:8085 
    expose:
    - 8085
    depends_on:
    - mysql
    
  movie-app:
    image: movie-app
    build: MovieCruiserBackend/
    restart: always
    network_mode: host
    ports:
    - 8082:8082 
    expose:
    - 8082
    depends_on:
    - mysql

  mysql:   
   image: mysql:5.5
   ports:
   - "3306:3306"
   network_mode: host
   environment:
    MYSQL_DATABASE: movieDb
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: app_root
    MYSQL_PASSWORD: root123   
  angular-app:
   image: angular-app
   build: movie-cruiser-capsule-frontend/
   network_mode: host
   container_name: angular-docker
   ports:
   - 4200:4200   