spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/movieDb
    #username: root
    #password: root
    url: ${MYSQL_CI_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
     hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8085